---
- hosts: all
  vars:
    env:
      DEBIAN_FRONTEND: "noninteractive"
  sudo: yes # On EC2 nodes, this is automatically passwordless.
  gather_facts: True  #We need to re-enable this, as we turned it off earlier.
  vars_files:
    - .aws_vars.yml
    - .repo.yml
  tasks:
    - name: update various utils
      command: "apt-get -y install {{ item }}"
      with_items:
        - ntp
        - unzip

  roles:
    - { role: nginx, wibble: true }
    - { role: php-fpm, wibble: true }
    - { role: mysql, wibble: true }
    - { role: wordpress, wp_root: /srv/www/wordpress, custom_root: /srv/www/custom }

