---
- name: update various utils
  command: "apt-get -y install {{ item }}"
  with_items:
    - git
    - curl

- name: Make /srv/www
  file: dest=/srv/www mode=755 owner=www-data group=www-data state=directory

- name: Download Wordpress
  get_url: url=http://wordpress.org/wordpress-{{ wp_version }}.tar.gz dest=/srv/www/wordpress-{{ wp_version }}.tar.gz
           sha256sum="{{ wp_sha256sum }}"

- name: Extract archive
  command: chdir=/srv/www/ /bin/tar xvf wordpress-{{ wp_version }}.tar.gz creates={{ wp_root }}

- name: Fetch random salts for Wordpress config
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"
  sudo: no

- name: Create Wordpress database
  mysql_db: name={{ wp_db_name }} state=present

- name: Create Wordpress database user
  mysql_user: name={{ wp_db_user }} password={{ wp_db_password }} priv={{ wp_db_name }}.*:ALL host='localhost' state=present

- name: Copy Wordpress config file
  template: src=wp-config.php dest={{ wp_root }}/

- name: Change ownership of Wordpress installation
  file: path={{ wp_root }}/ owner=www-data group=www-data state=directory recurse=yes

- name: Copy /etc/nginx/sites-enabled/default.conf
  template: src=sites/default.conf dest=/etc/nginx/sites-enabled/default.conf

- name: Copy /etc/nginx/nginx.conf
  template: src=nginx.conf dest=/etc/nginx/nginx.conf

- name: Copy wp nginx configuration
  template: src=nginx-wp-common.conf dest=/etc/nginx/nginx-wp-common.conf
  notify: restart nginx

# wp-cli instructions from http://wp-cli.org/
- name: wp-cli.phar download
  shell:
    curl -L https://raw.github.com/wp-cli/builds/gh-pages/phar/wp-cli.phar -o /root/wp-cli.phar
    creates=/root/wp-cli.phar

- name: wp-cli Clone/Update
  git: repo=git://github.com/wp-cli/wp-cli.git
       dest=/srv/www/wp-cli

- name: Install WP site
  command: chdir={{ wp_root }} /usr/bin/php /root/wp-cli.phar core install --url={{ server_hostname }} --quiet --title='{{ site_name }}' --admin_name={{ admin_name }} --admin_email={{ admin_email }} --admin_password={{ admin_password }} --allow-root

- name: Install WP Plugins
  command: chdir={{ wp_root }} /usr/bin/php /root/wp-cli.phar plugin install {{ item }} --allow-root
  with_items: base_plugins

- name: Activate WP Plugins
  command: chdir={{ wp_root }} /usr/bin/php /root/wp-cli.phar plugin activate {{ item }} --allow-root
  with_items: base_plugins

# Include custom git repo if defined in .private_vars.yml
- include: custom.yml
  when: custom_repo is defined
